export { Hero } from './Hero'
export { Benefits } from './Benefits'
export { Process } from './Process'
export { WhoItsFor } from './WhoItsFor'
export { FAQ } from './FAQ'
export { FinalCTA } from './FinalCTA'
